"use client";

import { useState, useRef } from "react";

type SoapNote = {
  subjective: string;
  objective: string;
  assessment: string;
  plan: string;
};

type GenerateResult = {
  soap: SoapNote;
  discharge: string;
};

type View = "landing" | "app" | "results";

export default function Home() {
  const [view, setView] = useState<View>("landing");
  const [loading, setLoading] = useState(false);
  const [loadingAudio, setLoadingAudio] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState<GenerateResult | null>(null);
  const [audioSrc, setAudioSrc] = useState<string | null>(null);
  const audioRef = useRef<HTMLAudioElement>(null);
  const [copied, setCopied] = useState<string | null>(null);

  const [form, setForm] = useState({
    patientName: "",
    species: "Dog",
    breed: "",
    age: "",
    sex: "Male (Neutered)",
    weight: "",
    ownerName: "",
    chiefComplaint: "",
    examNotes: "",
  });

  function handleChange(
    e: React.ChangeEvent<
      HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
    >
  ) {
    setForm((prev) => ({ ...prev, [e.target.name]: e.target.value }));
  }

  async function handleGenerate(e: React.FormEvent) {
    e.preventDefault();
    if (!form.chiefComplaint.trim() || !form.examNotes.trim()) {
      setError("Chief complaint and exam notes are required.");
      return;
    }
    setError("");
    setLoading(true);
    setAudioSrc(null);
    try {
      const res = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
      const data = await res.json();
      if (!res.ok || data.error) throw new Error(data.error || "Generation failed");
      setResult(data);
      setView("results");
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  }

  async function handleSpeak() {
    if (!result) return;
    setLoadingAudio(true);
    try {
      const res = await fetch("/api/speak", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text: result.discharge }),
      });
      const data = await res.json();
      if (!res.ok || data.error) throw new Error(data.error);
      const src = `data:${data.mimeType};base64,${data.audio}`;
      setAudioSrc(src);
      setTimeout(() => audioRef.current?.play(), 100);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Audio failed");
    } finally {
      setLoadingAudio(false);
    }
  }

  function copyText(text: string, key: string) {
    navigator.clipboard.writeText(text);
    setCopied(key);
    setTimeout(() => setCopied(null), 2000);
  }

  function copySoap() {
    if (!result) return;
    const s = result.soap;
    const full = `SOAP NOTE\n\nSUBJECTIVE:\n${s.subjective}\n\nOBJECTIVE:\n${s.objective}\n\nASSESSMENT:\n${s.assessment}\n\nPLAN:\n${s.plan}`;
    copyText(full, "soap");
  }

  function downloadSoap() {
    if (!result) return;
    const s = result.soap;
    const full = `SOAP NOTE — ${form.patientName || "Patient"}\nGenerated by VetScript\n\nSUBJECTIVE:\n${s.subjective}\n\nOBJECTIVE:\n${s.objective}\n\nASSESSMENT:\n${s.assessment}\n\nPLAN:\n${s.plan}\n\n---\nOWNER DISCHARGE SUMMARY:\n${result.discharge}`;
    const blob = new Blob([full], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `vetscript-${(form.patientName || "patient").toLowerCase().replace(/\s+/g, "-")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function downloadAudio() {
    if (!audioSrc) return;
    const a = document.createElement("a");
    a.href = audioSrc;
    a.download = `discharge-${(form.patientName || "patient").toLowerCase().replace(/\s+/g, "-")}.mp3`;
    a.click();
  }

  // ─── LANDING PAGE ─────────────────────────────────────────────────────────
  if (view === "landing") {
    return (
      <div className="min-h-screen bg-white">
        {/* Nav */}
        <nav className="flex items-center justify-between px-8 py-5 max-w-6xl mx-auto">
          <div className="flex items-center gap-2">
            <span className="text-2xl">🐾</span>
            <span className="text-xl font-bold text-slate-900">VetScript</span>
          </div>
          <div className="flex items-center gap-6">
            <a href="#pricing" className="text-slate-600 hover:text-slate-900 text-sm font-medium">Pricing</a>
            <button
              onClick={() => setView("app")}
              className="bg-teal-600 text-white px-5 py-2 rounded-lg text-sm font-semibold hover:bg-teal-700 transition-colors"
            >
              Try Free
            </button>
          </div>
        </nav>

        {/* Hero */}
        <section className="max-w-4xl mx-auto px-8 pt-20 pb-24 text-center">
          <div className="inline-flex items-center gap-2 bg-teal-50 border border-teal-200 rounded-full px-4 py-1.5 text-sm text-teal-700 font-medium mb-8">
            <span className="w-2 h-2 bg-teal-500 rounded-full inline-block"></span>
            New: Voice discharge summaries via ElevenLabs
          </div>
          <h1 className="text-5xl font-extrabold text-slate-900 leading-tight mb-6">
            SOAP notes done<br />
            <span className="text-teal-600">before the next patient.</span>
          </h1>
          <p className="text-xl text-slate-500 max-w-2xl mx-auto mb-10 leading-relaxed">
            Speak your exam notes. VetScript writes the SOAP note, the owner discharge summary, and reads it aloud so you can send the audio directly to the owner.
          </p>
          <div className="flex gap-4 justify-center flex-wrap">
            <button
              onClick={() => setView("app")}
              className="bg-teal-600 text-white px-8 py-3.5 rounded-xl text-base font-semibold hover:bg-teal-700 transition-colors shadow-lg shadow-teal-200"
            >
              Generate a note now — free
            </button>
            <a
              href="#how-it-works"
              className="border border-slate-200 text-slate-700 px-8 py-3.5 rounded-xl text-base font-semibold hover:bg-slate-50 transition-colors"
            >
              See how it works
            </a>
          </div>
          <p className="text-sm text-slate-400 mt-4">No credit card. No account needed. 10 free notes/month.</p>
        </section>

        {/* Stats strip */}
        <div className="bg-slate-900 py-10">
          <div className="max-w-4xl mx-auto px-8 grid grid-cols-3 gap-8 text-center">
            {[
              { stat: "25 min", label: "Average saved per patient" },
              { stat: "3 sec", label: "SOAP note generation time" },
              { stat: "100%", label: "Blameless — vet reviews before sending" },
            ].map((item) => (
              <div key={item.label}>
                <div className="text-3xl font-extrabold text-teal-400">{item.stat}</div>
                <div className="text-slate-400 text-sm mt-1">{item.label}</div>
              </div>
            ))}
          </div>
        </div>

        {/* How it works */}
        <section id="how-it-works" className="max-w-5xl mx-auto px-8 py-24">
          <h2 className="text-3xl font-bold text-slate-900 text-center mb-4">Three steps. Zero paperwork.</h2>
          <p className="text-slate-500 text-center mb-14 text-lg">Replace 25 minutes of typing with 60 seconds of speaking.</p>
          <div className="grid grid-cols-3 gap-8">
            {[
              {
                step: "1",
                icon: "🎙",
                title: "Speak or type your notes",
                desc: "Dictate your exam findings the way you naturally think — messy, abbreviated, incomplete. VetScript gets it.",
              },
              {
                step: "2",
                icon: "📋",
                title: "Get your SOAP note",
                desc: "A properly formatted Subjective / Objective / Assessment / Plan note, ready to paste into your PMS.",
              },
              {
                step: "3",
                icon: "🔊",
                title: "Send the audio discharge",
                desc: "One click generates an MP3 of the discharge summary read aloud. Text it to the owner before they leave the parking lot.",
              },
            ].map((item) => (
              <div key={item.step} className="bg-slate-50 rounded-2xl p-8 border border-slate-100">
                <div className="text-4xl mb-4">{item.icon}</div>
                <div className="text-xs font-bold text-teal-600 uppercase tracking-wider mb-2">Step {item.step}</div>
                <h3 className="font-bold text-slate-900 text-lg mb-3">{item.title}</h3>
                <p className="text-slate-500 text-sm leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Pricing */}
        <section id="pricing" className="bg-slate-50 py-24">
          <div className="max-w-4xl mx-auto px-8 text-center">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">Simple, per-vet pricing</h2>
            <p className="text-slate-500 mb-14 text-lg">One subscription per vet. Unlimited notes. Cancel anytime.</p>
            <div className="grid grid-cols-3 gap-6">
              {[
                {
                  name: "Starter",
                  price: "$0",
                  period: "forever",
                  features: ["10 notes/month", "SOAP notes only", "Copy & download", "No audio"],
                  cta: "Get started",
                  highlight: false,
                },
                {
                  name: "Solo Vet",
                  price: "$79",
                  period: "per month",
                  features: [
                    "Unlimited notes",
                    "SOAP + discharge summaries",
                    "Voice audio (ElevenLabs)",
                    "Export to PDF",
                    "Email to owner",
                  ],
                  cta: "Start free trial",
                  highlight: true,
                },
                {
                  name: "Clinic",
                  price: "$199",
                  period: "per month",
                  features: [
                    "Up to 8 vets",
                    "Everything in Solo",
                    "Custom clinic branding on audio",
                    "PMS export (PIMS CSV)",
                    "Priority support",
                  ],
                  cta: "Contact us",
                  highlight: false,
                },
              ].map((plan) => (
                <div
                  key={plan.name}
                  className={`rounded-2xl p-8 border ${
                    plan.highlight
                      ? "bg-teal-600 border-teal-600 text-white shadow-xl shadow-teal-200"
                      : "bg-white border-slate-200"
                  }`}
                >
                  <div className={`text-sm font-bold uppercase tracking-wider mb-2 ${plan.highlight ? "text-teal-100" : "text-slate-500"}`}>
                    {plan.name}
                  </div>
                  <div className={`text-4xl font-extrabold mb-1 ${plan.highlight ? "text-white" : "text-slate-900"}`}>
                    {plan.price}
                  </div>
                  <div className={`text-sm mb-6 ${plan.highlight ? "text-teal-200" : "text-slate-400"}`}>{plan.period}</div>
                  <ul className="space-y-3 mb-8">
                    {plan.features.map((f) => (
                      <li key={f} className={`text-sm flex items-center gap-2 ${plan.highlight ? "text-teal-50" : "text-slate-600"}`}>
                        <span className={plan.highlight ? "text-teal-200" : "text-teal-500"}>✓</span>
                        {f}
                      </li>
                    ))}
                  </ul>
                  <button
                    onClick={() => setView("app")}
                    className={`w-full py-3 rounded-xl font-semibold text-sm transition-colors ${
                      plan.highlight
                        ? "bg-white text-teal-700 hover:bg-teal-50"
                        : "border border-slate-200 text-slate-700 hover:bg-slate-50"
                    }`}
                  >
                    {plan.cta}
                  </button>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Footer */}
        <footer className="py-8 text-center text-slate-400 text-sm border-t border-slate-100">
          <p>VetScript — AI clinical notes for veterinarians.</p>
          <p className="mt-1">Not a substitute for clinical judgment. Always review before finalising records.</p>
        </footer>
      </div>
    );
  }

  // ─── APP (INPUT FORM) ──────────────────────────────────────────────────────
  if (view === "app") {
    return (
      <div className="min-h-screen bg-slate-50">
        {/* Header */}
        <div className="bg-white border-b border-slate-200 px-8 py-4 flex items-center gap-3">
          <button onClick={() => setView("landing")} className="text-slate-400 hover:text-slate-700 text-sm">
            ← Back
          </button>
          <span className="text-slate-300">|</span>
          <span className="text-2xl">🐾</span>
          <span className="font-bold text-slate-900">VetScript</span>
          <span className="ml-auto text-sm text-slate-400">AI Exam Note Generator</span>
        </div>

        <div className="max-w-3xl mx-auto px-8 py-12">
          <h1 className="text-2xl font-bold text-slate-900 mb-1">New Exam Note</h1>
          <p className="text-slate-500 text-sm mb-8">Fill in what you know, paste your rough notes. VetScript does the rest.</p>

          <form onSubmit={handleGenerate} className="space-y-6">
            {/* Patient Details */}
            <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm">
              <h2 className="font-semibold text-slate-800 mb-4 text-sm uppercase tracking-wider">Patient Details</h2>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="text-xs font-medium text-slate-500 block mb-1">Patient Name</label>
                  <input
                    name="patientName"
                    value={form.patientName}
                    onChange={handleChange}
                    placeholder="Buddy"
                    className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-teal-500"
                  />
                </div>
                <div>
                  <label className="text-xs font-medium text-slate-500 block mb-1">Owner Name</label>
                  <input
                    name="ownerName"
                    value={form.ownerName}
                    onChange={handleChange}
                    placeholder="Jane Smith"
                    className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-teal-500"
                  />
                </div>
                <div>
                  <label className="text-xs font-medium text-slate-500 block mb-1">Species</label>
                  <select
                    name="species"
                    value={form.species}
                    onChange={handleChange}
                    className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-teal-500"
                  >
                    <option>Dog</option>
                    <option>Cat</option>
                    <option>Rabbit</option>
                    <option>Bird</option>
                    <option>Reptile</option>
                    <option>Small mammal</option>
                    <option>Other</option>
                  </select>
                </div>
                <div>
                  <label className="text-xs font-medium text-slate-500 block mb-1">Breed</label>
                  <input
                    name="breed"
                    value={form.breed}
                    onChange={handleChange}
                    placeholder="Labrador Retriever"
                    className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-teal-500"
                  />
                </div>
                <div>
                  <label className="text-xs font-medium text-slate-500 block mb-1">Age (years)</label>
                  <input
                    name="age"
                    value={form.age}
                    onChange={handleChange}
                    placeholder="3"
                    className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-teal-500"
                  />
                </div>
                <div>
                  <label className="text-xs font-medium text-slate-500 block mb-1">Sex</label>
                  <select
                    name="sex"
                    value={form.sex}
                    onChange={handleChange}
                    className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-teal-500"
                  >
                    <option>Male (Intact)</option>
                    <option>Male (Neutered)</option>
                    <option>Female (Intact)</option>
                    <option>Female (Spayed)</option>
                  </select>
                </div>
                <div>
                  <label className="text-xs font-medium text-slate-500 block mb-1">Weight (kg)</label>
                  <input
                    name="weight"
                    value={form.weight}
                    onChange={handleChange}
                    placeholder="28.4"
                    className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-teal-500"
                  />
                </div>
              </div>
            </div>

            {/* Clinical Info */}
            <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm">
              <h2 className="font-semibold text-slate-800 mb-4 text-sm uppercase tracking-wider">Clinical Information</h2>
              <div className="space-y-4">
                <div>
                  <label className="text-xs font-medium text-slate-500 block mb-1">
                    Chief Complaint <span className="text-red-400">*</span>
                  </label>
                  <input
                    name="chiefComplaint"
                    value={form.chiefComplaint}
                    onChange={handleChange}
                    required
                    placeholder="e.g. Vomiting x2 days, lethargy"
                    className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-teal-500"
                  />
                </div>
                <div>
                  <label className="text-xs font-medium text-slate-500 block mb-1">
                    Your Exam Notes <span className="text-red-400">*</span>
                    <span className="font-normal text-slate-400 ml-2">— rough, abbreviated, whatever you have</span>
                  </label>
                  <textarea
                    name="examNotes"
                    value={form.examNotes}
                    onChange={handleChange}
                    required
                    rows={8}
                    placeholder={`Example:\nHR 120, RR 24, temp 39.1, BCS 5/9. MM pink moist, CRT <2s. Mild dehydration ~5%. Abdomen — diffuse pain on palpation mid abdomen, no masses. No vomiting in clinic. Ate grass yesterday per owner. Diet — kibble + table scraps. Vax UTD. No meds. Ddx: dietary indiscretion vs gastroenteritis vs foreign body. Rec: SQ fluids 250ml LRS, metronidazole 15mg/kg PO BID x5d, bland diet, recheck in 3d if not improving.`}
                    className="w-full border border-slate-200 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-teal-500 resize-none font-mono"
                  />
                </div>
              </div>
            </div>

            {error && (
              <div className="bg-red-50 border border-red-200 text-red-700 rounded-lg px-4 py-3 text-sm">
                {error}
              </div>
            )}

            <button
              type="submit"
              disabled={loading}
              className="w-full bg-teal-600 hover:bg-teal-700 disabled:bg-teal-400 text-white py-4 rounded-xl font-semibold text-base transition-colors shadow-lg shadow-teal-100 flex items-center justify-center gap-2"
            >
              {loading ? (
                <>
                  <svg className="animate-spin h-5 w-5" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                  </svg>
                  Generating notes...
                </>
              ) : (
                "Generate SOAP Note + Discharge Summary"
              )}
            </button>
          </form>
        </div>
      </div>
    );
  }

  // ─── RESULTS ───────────────────────────────────────────────────────────────
  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <div className="bg-white border-b border-slate-200 px-8 py-4 flex items-center gap-3">
        <button
          onClick={() => { setView("app"); setResult(null); setAudioSrc(null); }}
          className="text-slate-400 hover:text-slate-700 text-sm"
        >
          ← New note
        </button>
        <span className="text-slate-300">|</span>
        <span className="text-2xl">🐾</span>
        <span className="font-bold text-slate-900">VetScript</span>
        <span className="ml-auto flex gap-2">
          <button
            onClick={copySoap}
            className="text-sm text-slate-600 border border-slate-200 rounded-lg px-3 py-1.5 hover:bg-slate-50 transition-colors"
          >
            {copied === "soap" ? "Copied!" : "Copy SOAP"}
          </button>
          <button
            onClick={downloadSoap}
            className="text-sm bg-teal-600 text-white rounded-lg px-3 py-1.5 hover:bg-teal-700 transition-colors"
          >
            Download .txt
          </button>
        </span>
      </div>

      <div className="max-w-4xl mx-auto px-8 py-10 space-y-6">
        {/* Patient badge */}
        <div className="bg-teal-50 border border-teal-200 rounded-xl px-5 py-3 flex items-center gap-3">
          <span className="text-2xl">🐾</span>
          <div>
            <span className="font-semibold text-teal-900">
              {form.patientName || "Patient"} — {form.species} {form.breed ? `(${form.breed})` : ""}
            </span>
            {form.ownerName && (
              <span className="text-teal-600 text-sm ml-2">Owner: {form.ownerName}</span>
            )}
          </div>
          <div className="ml-auto flex items-center gap-2 text-sm text-teal-600">
            <span className="w-2 h-2 bg-teal-500 rounded-full inline-block"></span>
            Generated by VetScript
          </div>
        </div>

        {/* SOAP Note */}
        {result && (
          <div className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden">
            <div className="border-b border-slate-100 px-6 py-4 flex items-center justify-between">
              <h2 className="font-bold text-slate-900">SOAP Note</h2>
              <button
                onClick={copySoap}
                className="text-xs text-slate-500 border border-slate-200 rounded-lg px-3 py-1.5 hover:bg-slate-50 transition-colors"
              >
                {copied === "soap" ? "Copied!" : "Copy all"}
              </button>
            </div>
            {(
              [
                { key: "S", label: "Subjective", text: result.soap.subjective, color: "bg-blue-50 border-blue-200 text-blue-800" },
                { key: "O", label: "Objective", text: result.soap.objective, color: "bg-slate-50 border-slate-200 text-slate-800" },
                { key: "A", label: "Assessment", text: result.soap.assessment, color: "bg-amber-50 border-amber-200 text-amber-800" },
                { key: "P", label: "Plan", text: result.soap.plan, color: "bg-teal-50 border-teal-200 text-teal-800" },
              ] as Array<{ key: string; label: string; text: string; color: string }>
            ).map((section) => (
              <div key={section.key} className="px-6 py-5 border-b border-slate-50 last:border-0">
                <div className="flex items-start gap-4">
                  <div className={`flex-shrink-0 w-8 h-8 rounded-lg border flex items-center justify-center font-bold text-sm ${section.color}`}>
                    {section.key}
                  </div>
                  <div className="flex-1">
                    <div className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1.5">{section.label}</div>
                    <p className="text-sm text-slate-700 leading-relaxed whitespace-pre-wrap">{section.text}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Discharge Summary */}
        {result && (
          <div className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden">
            <div className="border-b border-slate-100 px-6 py-4 flex items-center justify-between">
              <div>
                <h2 className="font-bold text-slate-900">Owner Discharge Summary</h2>
                <p className="text-xs text-slate-400 mt-0.5">Plain language. Ready to print, email, or speak.</p>
              </div>
              <button
                onClick={() => copyText(result.discharge, "discharge")}
                className="text-xs text-slate-500 border border-slate-200 rounded-lg px-3 py-1.5 hover:bg-slate-50 transition-colors"
              >
                {copied === "discharge" ? "Copied!" : "Copy text"}
              </button>
            </div>
            <div className="px-6 py-5">
              <p className="text-sm text-slate-700 leading-relaxed whitespace-pre-wrap">{result.discharge}</p>
            </div>

            {/* Audio section */}
            <div className="border-t border-slate-100 bg-slate-50 px-6 py-5">
              <div className="flex items-center gap-4 flex-wrap">
                <div>
                  <div className="text-sm font-semibold text-slate-800 mb-0.5">Voice Discharge Audio</div>
                  <div className="text-xs text-slate-400">Generate an MP3 to send to the owner via text or WhatsApp.</div>
                </div>
                <div className="flex gap-2 ml-auto flex-wrap items-center">
                  {!audioSrc ? (
                    <button
                      onClick={handleSpeak}
                      disabled={loadingAudio}
                      className="bg-teal-600 text-white text-sm px-5 py-2 rounded-lg font-semibold hover:bg-teal-700 disabled:bg-teal-400 transition-colors flex items-center gap-2"
                    >
                      {loadingAudio ? (
                        <>
                          <svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                          </svg>
                          Generating audio...
                        </>
                      ) : (
                        "🔊 Generate audio"
                      )}
                    </button>
                  ) : (
                    <>
                      <audio ref={audioRef} src={audioSrc} controls className="h-10 rounded-lg" />
                      <button
                        onClick={downloadAudio}
                        className="border border-teal-300 text-teal-700 text-sm px-4 py-2 rounded-lg font-semibold hover:bg-teal-50 transition-colors"
                      >
                        Download MP3
                      </button>
                    </>
                  )}
                </div>
              </div>
              {error && (
                <div className="mt-3 text-red-600 text-xs">{error}</div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
